canvas vue done
Applied-Research-Winter-2022/Pozter pull request #12
Opened 2022-03-17 14:20 UTC by saloohi

## Link Jira ticket:
https://jess-nguy.atlassian.net/browse/POZ-29

## Author Notes:
this was fun!

## Impacts and Notes:
I added a pozter.png logo file.

## Testing Guidance:
run frontend and go to localhost:8080/create/2

## Author Checklist:

- [x] Tested locally.
- [x] Change Jira ticket status to Review.
- [n/a ] Updated the documentation.

2022-03-17 15:33 UTC, jpdh9881 commented
this looks really cool but i think it reflects the User Content page. The Screen Canvas page is where the user selects one of the Screen Canvases that is associated with the Billboard the user selects.

the process is:
1) select Billboard
2) select a Screen Canvas. a billboard can have multiple screen canvases (e.g. a screen canvas with 1 screen, a screen canvas with 3 separate screens, etc.).
3) set user content (add the photo)
4) social media

More details can be found [here](https://app.diagrams.net/#G1w-_Va39xHu_rnMdN1H9-iuXcPjP_g_kF)

any questions please let me know!

2022-03-17 22:12 UTC, jpdh9881 approved these changes

2022-03-18 14:35 UTC, Jess-Nguy commented
```
  <img src="../../assets/pozter.png" contain alt="Pozter" />
```
You have this line in `front-end\src\views\create\Canvas.vue` but since this isn't in this branch or main yet, you can't fully run this. You'll either have to wait til https://github.com/Applied-Research-Winter-2022/Pozter/pull/14/files  or this https://github.com/Applied-Research-Winter-2022/Pozter/pull/13/files gets merged first. Or merge this into one of those branches. 

Tip: If you're working on chained branches you can break them into pieces like you did but instead of merging to main you can merge to the branch/pull request you're building on top of. Click `edit` then change the branch this will merge into. 
![image](https://user-images.githubusercontent.com/38814279/159022767-c46bdee3-6c6f-441f-a9c9-a3917ae9979b.png)

2022-03-18 14:44 UTC, Jess-Nguy requested changes
Other than the missing img this looks good. Please do one of the following steps I provided in the comment above so that we don't get a merge conflict or to not have any errors in main.

![image](https://user-images.githubusercontent.com/38814279/159024377-13e0bf11-6b7a-44c3-887a-8634852ab3ea.png)

2022-03-18 14:49 UTC, merged