Add files via upload
Applied-Research-Winter-2022/Pozter pull request #4
Opened 2022-02-23 03:30 UTC by saloohi

## Link Jira ticket:
https://jess-nguy.atlassian.net/browse/POZ-9

## Author Notes:

In your own words, what does this code change accomplish?
it's a frontend boilerplate for the team to build on and go back to JIC. 

## Impacts and Notes:

_Include notes about what the reviewer should consider when assessing the code changes._

## Testing Guidance:

_Write out how the reviewer could test the changes introduced in this PR._

## Author Checklist:

- [ ] Tested locally.
- [ ] Change Jira ticket status to Review.
- [ ] Updated the documentation.

2022-02-23 18:08 UTC, jpdh9881 requested changes
Please see updated instructions in the JIRA ticket

2022-02-24 15:59 UTC, jpdh9881 commented
everything looks great except that the .gitignore file seems to have been deleted in the main directory, allowing the node_modules folder in /server to be included in the git project. (the git ignore file tells git to ignore certain files and folders which should not be tracked in the repository. Including the node_modules folder makes the project unnecessarily big and can cause problems later on)
i think the best bet to fix this would be to:
1) switch to the main branch (git checkout main)
2) create a new POZ-9 branch (git checkout -b POZ-9-version-2)
3) install the vue project as before
4) finish the PR!

2022-02-24 16:54 UTC, Jess-Nguy commented
You can also follow these steps to merge main into this branch
```
git checkout dmgr2      # gets you "on branch dmgr2"
git fetch origin        # gets you up to date with origin
git merge origin/master
```
Please make sure you add reviewers to let people know you're ready for people to look at this.

2022-02-24 16:58 UTC, Jess-Nguy reviewed
I agree with with Joe said, let's revert the `.gitignore` so we don't have the node module  in the repo
to revert by commit do the following:
`git revert <commit number>`

2022-02-24 16:58 UTC, Jess-Nguy commented on README.md
> -# Project setup:
Please leave the previous readme details and add more if you'd like. 
It looks like you add your pull request details into the readme which shouldn't be here.

2022-02-24 16:58 UTC, Jess-Nguy commented on front-end/README.md
> +# front-end
Lets combine this readme with the root readme

2022-02-24 19:57 UTC, closed without merging